Trends Page: Add labels
BinaryStudioAcademy/bsa-2021-hypecrafter pull request #129
Opened 2021-08-19 11:34 UTC by DarkFlamingo

2021-08-19 16:48 UTC, DarkFlamingo commented
![image](https://user-images.githubusercontent.com/59978115/130110050-4d9e31e0-fc7e-4255-aa4f-365e8999c1ca.png)

2021-08-19 17:36 UTC, yevhenii-moroziuk requested changes

2021-08-19 17:36 UTC, yevhenii-moroziuk commented on frontend/src/scenes/TrendsPage/components/ProjectsChart/ChartLabels/Label/index.tsx
> +      <p className={classes.data}>{`${project.views} views`}</p>
Do not forget about localization

2021-08-19 17:36 UTC, yevhenii-moroziuk commented on frontend/src/scenes/TrendsPage/components/ProjectsChart/ChartLabels/Label/index.tsx
> +      <p className={classes.name}>{сutWord(project.name, 22)}</p>
Use constant

2021-08-19 17:36 UTC, yevhenii-moroziuk commented on frontend/src/scenes/TrendsPage/options/ProjectsOptions.ts
> +/* eslint-disable */
Why do you need to use eslint-disable?

2021-08-19 17:42 UTC, DarkFlamingo commented on frontend/src/scenes/TrendsPage/options/ProjectsOptions.ts
> +/* eslint-disable */
I use it because I have unused parameters in the function

2021-08-19 17:43 UTC, yevhenii-moroziuk commented on frontend/src/scenes/TrendsPage/options/ProjectsOptions.ts
> +/* eslint-disable */
u can use prefix _

2021-08-19 17:46 UTC, DarkFlamingo commented on frontend/src/scenes/TrendsPage/options/ProjectsOptions.ts
> +/* eslint-disable */
Thank you very much I do not know about such opportunity

2021-08-19 17:48 UTC, DarkFlamingo commented on frontend/src/scenes/TrendsPage/components/ProjectsChart/ChartLabels/Label/index.tsx
> +      <p className={classes.name}>{сutWord(project.name, 22)}</p>
For color ?

2021-08-19 17:52 UTC, DarkFlamingo commented on frontend/src/scenes/TrendsPage/components/ProjectsChart/ChartLabels/Label/index.tsx
> +      <p className={classes.name}>{сutWord(project.name, 22)}</p>
I give this component colors that I take from the helper

2021-08-20 05:05 UTC, yevhenii-moroziuk commented on frontend/src/scenes/TrendsPage/components/ProjectsChart/ChartLabels/Label/index.tsx
> +      <p className={classes.name}>{сutWord(project.name, 22)}</p>
for magic number 22

2021-08-20 10:07 UTC, yevhenii-moroziuk approved these changes

2021-08-20 10:08 UTC, merged