Bug fix header
BinaryStudioAcademy/bsa-2021-hypecrafter pull request #137
Opened 2021-08-21 10:29 UTC by maksim-luzin

2021-08-21 10:29 UTC, maksim-luzin commented
[https://imgur.com/WkAneXW](url)

2021-08-21 10:39 UTC, maksim-luzin commented
https://user-images.githubusercontent.com/64692611/130319217-fb955178-5d48-431b-a439-d84e4ac91f10.mp4

2021-08-21 20:45 UTC, maksim-luzin commented
![sreencapture-11](https://user-images.githubusercontent.com/64692611/130334371-99d59173-f2b5-496c-ac30-5258a3dc04c8.png)

2021-08-23 09:40 UTC, yevhenii-moroziuk requested changes

2021-08-23 09:40 UTC, yevhenii-moroziuk commented on frontend/src/scenes/Auth/SignupPage/styles.module.scss
> +@import "../../../styles/mixins", "../../../styles/vars";
Use single quotes, please

2021-08-23 11:02 UTC, yevhenii-moroziuk requested changes

2021-08-23 11:02 UTC, yevhenii-moroziuk commented on frontend/src/scenes/CreateProject/components/Layout/styles.module.scss
> +@import "../../../../styles/vars";
And here

2021-08-23 11:02 UTC, yevhenii-moroziuk commented on frontend/src/scenes/TrendsPage/styles.module.scss
> +@import "../../styles/vars";
And here, please

2021-08-23 11:02 UTC, yevhenii-moroziuk commented on frontend/src/scenes/Auth/SignupPage/styles.module.scss
>    font-size: $font-size-akcent;
Look like typo (accent)

2021-08-23 11:12 UTC, maksim-luzin commented on frontend/src/scenes/Auth/SignupPage/styles.module.scss
>    font-size: $font-size-akcent;
This is not my code. But I'll check it out now.

2021-08-23 11:46 UTC, merged