update useScroll hook behavior
BinaryStudioAcademy/bsa-2021-hypecrafter pull request #139
Opened 2021-08-22 09:47 UTC by buiiz

2021-08-22 16:44 UTC, maksim-luzin commented
Maybe, you better use window.pageYOffset.

2021-08-22 18:01 UTC, maksim-luzin approved these changes

2021-08-23 09:42 UTC, yevhenii-moroziuk requested changes

2021-08-23 09:42 UTC, yevhenii-moroziuk commented on frontend/src/hooks/useScroll.ts
> +  const getOffsetSize = () => window.pageYOffset;
Can we move this function out of the hook?

2021-08-23 09:47 UTC, buiiz commented on frontend/src/hooks/useScroll.ts
> +  const getOffsetSize = () => window.pageYOffset;
Yes, we can. I will fix it

2021-08-23 09:53 UTC, yevhenii-moroziuk approved these changes

2021-08-23 09:53 UTC, merged