Feat/cpp upload images on aws and add tags
BinaryStudioAcademy/bsa-2021-hypecrafter pull request #155
Opened 2021-08-26 07:49 UTC by Cuba49

2021-08-26 12:37 UTC, yevhenii-moroziuk requested changes

2021-08-26 12:37 UTC, yevhenii-moroziuk commented on frontend/src/scenes/CreateProject/components/Settings/index.tsx
> +  onChangeValue: (name: ProjectKeys, value: any) => void
you can use type for it

2021-08-26 12:37 UTC, yevhenii-moroziuk commented on frontend/src/scenes/CreateProject/components/Settings/index.tsx
> +          key={_tag.tag.name}
can we have just tag.name?

2021-08-26 12:37 UTC, yevhenii-moroziuk commented on backend/src/services/project/project.ts
> +    this.#projectTagRepository.save(listTags.map(_tag => ({ ...new ProjectTag(), tag: _tag, project })));
it would be nice to split logic between corresponding services

2021-08-28 17:22 UTC, yevhenii-moroziuk requested changes

2021-08-28 17:22 UTC, yevhenii-moroziuk commented on backend/src/services/project/project.ts
> +    const listTags = await new TagService(this.#tagRepository).save(body.projectTags.map(projectTag => projectTag.tag));
Pass this services as dependencies

2021-08-28 17:22 UTC, yevhenii-moroziuk commented on frontend/src/components/Input/index.tsx
> +            {options.slice(0, 10).map(option => (
What is 10? Let's use constant here

2021-08-28 17:22 UTC, yevhenii-moroziuk commented on frontend/src/scenes/CreateProject/components/Settings/index.tsx
> +const Settings: FC<Props> = ({ changePage, currentPage, onChangeValue, region, imageUrl, videoUrl, newTags }) => {
Read this [article]( https://blog.bitsrc.io/best-practices-with-react-hooks-69d7e4af69a7#:~:text=3.%20Create%20your%20function%20components%20in%20the%20right%20order), please:

2021-08-28 17:22 UTC, yevhenii-moroziuk commented on frontend/src/scenes/CreateProject/components/Settings/index.tsx
> +      newTags.push({ tag: { name: tag } });
Do not mutate props. Create action/pass callback. Also, you can use newTags.find()

2021-08-28 17:22 UTC, yevhenii-moroziuk commented on frontend/src/scenes/CreateProject/components/Settings/index.tsx
> +          {`${projectTag.tag.name}`}
{projectTag.tag.name}

2021-08-28 17:22 UTC, yevhenii-moroziuk commented on frontend/src/scenes/CreateProject/components/Settings/index.tsx
> +          // onBlur={() => setOptions([])}
comment

2021-08-31 07:47 UTC, buiiz commented on frontend/src/components/ImageUpload/styles.module.scss
> +    }
Here it should be 2 spaces offset, not 4

2021-08-31 07:47 UTC, buiiz commented on frontend/src/components/Input/index.tsx
> +            {options.slice(0, countOptions).map(option => (
2 spaces

2021-08-31 10:10 UTC, buiiz approved these changes

2021-08-31 14:16 UTC, yevhenii-moroziuk approved these changes

2021-09-01 12:52 UTC, merged