Feat/payment page
BinaryStudioAcademy/bsa-2021-hypecrafter pull request #161
Opened 2021-08-26 17:13 UTC by eluyema

2021-08-28 17:46 UTC, yevhenii-moroziuk requested changes

2021-08-28 17:46 UTC, yevhenii-moroziuk commented on frontend/src/scenes/Wallet/FundsPage/components/CustomFund/index.tsx
>            <Form.Control
use our input (we have number)

2021-08-28 17:46 UTC, yevhenii-moroziuk commented on frontend/src/scenes/Wallet/Payment/actions.ts
> +  SET_FUNDS = 'SET_FUNDS'
WALLET/SET_FUNDS

2021-08-28 17:46 UTC, yevhenii-moroziuk commented on frontend/src/scenes/Wallet/Payment/components/PaymentMenu/CheckoutForm/checkoutForm.tsx
> +  const [clientSecret, setClientSecret] = useState('');
Assumption: You can create a reducer or use useReducer

2021-08-28 17:46 UTC, yevhenii-moroziuk commented on frontend/src/scenes/Wallet/Payment/components/PaymentMenu/CheckoutForm/checkoutForm.tsx
> +  const handleChange = async (event: StripeCardElementChangeEvent) => {
Why async?

2021-08-28 17:46 UTC, yevhenii-moroziuk commented on frontend/src/scenes/Wallet/Payment/components/PaymentMenu/CheckoutForm/checkoutForm.tsx
> +    const params: ClientSecretData = { amount: amount.toString() };
Why amount is string?

2021-08-28 17:46 UTC, yevhenii-moroziuk commented on frontend/src/scenes/Wallet/Payment/components/PaymentMenu/CheckoutForm/checkoutForm.tsx
> +    <form id="payment-form" onSubmit={handleSubmit}>
Is it possible to use our form hook here?

2021-08-28 17:46 UTC, yevhenii-moroziuk commented on frontend/src/scenes/Wallet/Payment/components/PaymentMenu/CheckoutForm/checkoutForm.tsx
> +      {/* Show any error that happens when processing the payment */}
You don't need this comment

2021-08-28 17:46 UTC, yevhenii-moroziuk commented on frontend/src/scenes/Wallet/Payment/components/PaymentMenu/paymentMenu.tsx
> +  const promise = loadStripe(env.payment.key || '', { locale: 'en' });
Comments. And why promise?

2021-08-28 17:46 UTC, yevhenii-moroziuk commented on gateway/src/api/middlewares/authorization.ts
> +    if (route.includes('/:page')) return validatePage(route, req.path);
Optional: rewrite this helper to check any params

2021-08-28 17:46 UTC, yevhenii-moroziuk commented on payment/src/api/routes/payment.ts
> +    });
Move the logic to service and remove redundant console.logs

2021-08-28 17:46 UTC, yevhenii-moroziuk commented on payment/src/data/repositories/transactionHistory.ts
> +    newTransaction.userId = transaction.userId;
??????
![image](https://user-images.githubusercontent.com/57347573/131226430-a4acdfae-4c19-467c-984c-d021886025dc.png)

2021-08-30 14:36 UTC, buiiz commented on frontend/src/scenes/Wallet/Payment/components/SelectedFund/index.tsx
> +  const { isCustom, amount } = props;
it can be shortened

```js
const SelectedFund: FC<SuccessPageProps> = ({ isCustom, amount }) => {
```

2021-08-31 14:18 UTC, yevhenii-moroziuk approved these changes

2021-08-31 15:16 UTC, merged