Feat/add functionality to store current user
BinaryStudioAcademy/bsa-2021-hypecrafter pull request #17
Opened 2021-07-29 16:49 UTC by nickname038

2021-07-30 11:07 UTC, yevhenii-moroziuk requested changes

2021-07-30 11:07 UTC, yevhenii-moroziuk commented on frontend/src/components/Routing/index.tsx
> +    authUser();
dispatch action only if token exists and use enum StorageKey enum

2021-07-30 11:07 UTC, yevhenii-moroziuk commented on frontend/src/reducers/auth.ts
> +      error: action.payload
no need to store the error, we will kick out the user anyway

2021-07-30 11:07 UTC, yevhenii-moroziuk commented on frontend/src/actions/auth.ts
> +  AUTH = 'AUTH'
AUTH/FETCH_USER

2021-08-02 06:37 UTC, mtseluiko requested changes
resolve conflicts

2021-08-02 11:28 UTC, yevhenii-moroziuk approved these changes

2021-08-02 11:29 UTC, merged