fix id for user_profile
BinaryStudioAcademy/bsa-2021-hypecrafter pull request #170
Opened 2021-08-29 20:24 UTC by nickname038

2021-08-30 04:38 UTC, yevhenii-moroziuk requested changes

2021-08-30 04:38 UTC, yevhenii-moroziuk commented on gateway/src/api/routes/auth.ts
> +        const { firstName, lastName, email, region, phoneNumber, gender } = req.body;
req.body = { data: { ...req.body, id: userId }, tokens };

2021-08-30 06:16 UTC, nickname038 commented on gateway/src/api/routes/auth.ts
> +        const { firstName, lastName, email, region, phoneNumber, gender } = req.body;
req.body has a password field. This field not needed on backend

2021-08-31 14:19 UTC, yevhenii-moroziuk approved these changes

2021-09-01 12:56 UTC, merged