Add payment microservice.
BinaryStudioAcademy/bsa-2021-hypecrafter pull request #18
Opened 2021-07-29 17:08 UTC by maksim-luzin

2021-07-29 20:22 UTC, mtseluiko requested changes

2021-07-29 20:22 UTC, mtseluiko commented on package.json
> +        "start": "concurrently -k -p \"{name}: {time}\" -n \"FRONTEND,GATEWAY,BACKEND\" \"npm:start:frontend\" \"npm:start:gateway\" \"npm:start:backend\" \"npm:start:payment\""
also add PAYMENT title

2021-07-29 20:22 UTC, mtseluiko commented on package.json
> +    "scripts": {
use 2 spaces for tabs

2021-07-29 20:22 UTC, mtseluiko commented on payment/src/api/routes/index.ts
> +const initRoutes = (app: MicroMq) => paymentRouter(services, Path.Payment, app);
The "backend" microservice routing have changed. Please update here, as well.

2021-07-29 20:22 UTC, mtseluiko commented on payment/src/data/repositories/payment.ts
> +export class PaymentRepository {
Please, connect it also to database like in the Backend microservice

2021-07-29 20:24 UTC, mtseluiko commented on payment/src/server.ts
> +const { rabbit } = env.app;
connect this microservice to the gateway

2021-07-30 07:37 UTC, maksim-luzin commented on package.json
> +        "start": "concurrently -k -p \"{name}: {time}\" -n \"FRONTEND,GATEWAY,BACKEND\" \"npm:start:frontend\" \"npm:start:gateway\" \"npm:start:backend\" \"npm:start:payment\""
I added

2021-07-30 07:37 UTC, maksim-luzin commented on package.json
> +    "scripts": {
I rebuilt.

2021-07-30 07:39 UTC, mtseluiko commented on package.json
> +        "start": "concurrently -k -p \"{name}: {time}\" -n \"FRONTEND,GATEWAY,BACKEND\" \"npm:start:frontend\" \"npm:start:gateway\" \"npm:start:backend\" \"npm:start:payment\""
Here: -n \"FRONTEND,GATEWAY,BACKEND\"

2021-07-30 15:04 UTC, maksim-luzin commented on package.json
> +    "scripts": {
I corrected.

2021-07-30 15:04 UTC, maksim-luzin commented on payment/src/api/routes/index.ts
> +const initRoutes = (app: MicroMq) => paymentRouter(services, Path.Payment, app);
I changed.

2021-07-30 15:11 UTC, maksim-luzin commented on payment/src/data/repositories/payment.ts
> +export class PaymentRepository {
I examined the table and consulted with your colleague. Changed a little. It is now an associative donate table. It connects the user profile to projects.

2021-07-30 15:11 UTC, maksim-luzin commented on payment/src/server.ts
> +const { rabbit } = env.app;
I changed.

2021-07-30 21:00 UTC, mtseluiko commented on gateway/package.json
> +    "lint:write": "eslint . --ext .ts --fix"
why removed this?

2021-07-31 04:40 UTC, maksim-luzin commented on gateway/package.json
> +    "lint:write": "eslint . --ext .ts --fix"
I could create a migration when all models are in one place. Models in different microservices do not create migration.

2021-07-31 08:27 UTC, mtseluiko requested changes

2021-07-31 08:27 UTC, mtseluiko commented on package.json
> +      "concurrently": "^6.2.0",
spaces again. Please, check setups of autoformatting in your editor if it adds it automatically

2021-07-31 08:27 UTC, mtseluiko commented on gateway/package.json
> +    "lint:write": "eslint . --ext .ts --fix"
microservices should be independent. Maybe we'll even use separate databases

2021-07-31 08:27 UTC, mtseluiko commented on payment/src/data/entities/donate.ts
> +import { UserProfile } from '../../../../backend/src/data/entities/userProfile';
Please, remove this relation. Microservices should be independent. We'll store all payment transactions in the Payment database, and userId will be passed from the gateway/backend.

2021-07-31 09:25 UTC, maksim-luzin commented on gateway/package.json
> +    "lint:write": "eslint . --ext .ts --fix"
Good. Which table from the schema to use?

2021-07-31 09:26 UTC, maksim-luzin commented on package.json
> +      "concurrently": "^6.2.0",
Ok

2021-07-31 09:27 UTC, maksim-luzin commented on payment/src/data/entities/donate.ts
> +import { UserProfile } from '../../../../backend/src/data/entities/userProfile';
Good. Which table from the schema to use?

2021-08-02 06:35 UTC, mtseluiko commented on package.json
> +    "start": "concurrently -k -p \"{name}: {time}\" -n \"FRONTEND,GATEWAY,BACKEND,NOTIFICATION,PAYMENT\" \"npm:start:frontend\" \"npm:start:gateway\" \"npm:start:backend\" \"npm:start:notification\"
it seems, here were more scripts

2021-08-02 11:05 UTC, merged