Feat/add privileges on create project page
BinaryStudioAcademy/bsa-2021-hypecrafter pull request #182
Opened 2021-09-01 13:08 UTC by Cuba49

2021-09-03 20:53 UTC, DarkFlamingo commented on frontend/src/scenes/CreateProject/components/Privileges/components/donatorsPrivilege.tsx
> +      {/* <p>{t('Subparagraphs')}</p> */}
Delete commented code or should it be used in the future?

2021-09-03 20:53 UTC, DarkFlamingo commented on backend/src/services/projectPrivilege/projectPrivilege.ts
> +// import { DonatorsPrivilege } from '../../data/entities';
Delete commented code or should it be used in the future?

2021-09-05 18:15 UTC, yevhenii-moroziuk requested changes

2021-09-05 18:15 UTC, yevhenii-moroziuk commented on frontend/src/localization/locale-keys.d.ts
> +  | 'Press on me'
We use 2 spaces

2021-09-08 15:54 UTC, yevhenii-moroziuk approved these changes

2021-09-08 19:46 UTC, merged