featuer donators team chat
BinaryStudioAcademy/bsa-2021-hypecrafter pull request #185
Opened 2021-09-02 10:44 UTC by dgorkavyi

![другийСкрін](https://user-images.githubusercontent.com/22417499/131830375-522046ca-a0e5-49cb-a7c2-924aac786425.png)

2021-09-02 10:46 UTC, dgorkavyi commented
It is just a component without socket functionality yet

2021-09-03 07:28 UTC, Cuba49 requested changes

2021-09-03 07:28 UTC, Cuba49 commented on frontend/src/components/Chat/helpers.ts
> +  const currDateStr = new Date().toLocaleString(locale, timeZone).split(',');
Why we use USA time? May let the browser pick up the local time automatically

2021-09-03 07:28 UTC, Cuba49 commented on frontend/src/components/Chat/helpers.ts
> +  return currDateStr[0] === argDateStr[0]
need to cut a seconds, they overload the interface

2021-09-03 07:37 UTC, buiiz commented on frontend/src/components/Chat/ChatContent.tsx
> +const messageMapper = (mess: Message) => (
what is mess? i don't think that is a good variable name.

![Screenshot from 2021-09-03 10-28-26](https://user-images.githubusercontent.com/49621041/131967720-78ec7bf1-526a-472c-9e9f-f707ac8fbfe5.png)

2021-09-04 17:18 UTC, yevhenii-moroziuk commented on frontend/src/components/Chat/helpers.ts
> +  const currDateStr = new Date().toLocaleString(locale, timeZone).split(',');
use out time helper

2021-09-05 19:15 UTC, dgorkavyi commented
labels looks like: 
![image](https://user-images.githubusercontent.com/22417499/132138770-c20b4e8d-f991-439a-9fb8-318c82406cee.png)

2021-09-08 15:55 UTC, yevhenii-moroziuk approved these changes

2021-09-09 08:53 UTC, merged