Add login view
BinaryStudioAcademy/bsa-2021-hypecrafter pull request #189
Opened 2021-09-03 13:14 UTC by dolphin323

2021-09-05 18:48 UTC, yevhenii-moroziuk requested changes

2021-09-05 18:48 UTC, yevhenii-moroziuk commented on mobile/HypecrafterMobile/app/components/LoginView/LoginView.tsx
> +    backgroundColor: '#0aecec',
create files for colors, typography, etc

2021-09-06 12:54 UTC, niksonax commented on mobile/HypecrafterMobile/app/components/LoginView/LoginView.tsx
> +    backgroundColor: '#0aecec',
I've did this one already. You can find it at `app/styles/common.ts`

2021-09-06 20:21 UTC, yevhenii-moroziuk approved these changes

2021-09-08 15:55 UTC, merged