Feat/mobile main page
BinaryStudioAcademy/bsa-2021-hypecrafter pull request #191
Opened 2021-09-03 18:41 UTC by niksonax

2021-09-05 18:30 UTC, yevhenii-moroziuk requested changes

2021-09-05 18:30 UTC, yevhenii-moroziuk commented on mobile/HypecrafterMobile/app/App.tsx
> +          ref={(navigatorRef: any) => {
ref={NavigationService.setTopLevelNavigator} ?

2021-09-05 18:30 UTC, yevhenii-moroziuk commented on mobile/HypecrafterMobile/app/common/enums/category/category.ts
> +export enum CategoryType {
Do we have this enum in shared?

2021-09-05 18:30 UTC, yevhenii-moroziuk commented on mobile/HypecrafterMobile/app/common/enums/projects/projectsCategories.ts
> +declare enum Common {
do we need declare?

2021-09-05 18:30 UTC, yevhenii-moroziuk commented on mobile/HypecrafterMobile/app/components/MainView/screens/PopularScreen.tsx
> +  const renderItem: ListRenderItem<Project> = ({ item }) => (
This function will be re-created on every render. Since it doesn't use PopularScreen's props, move it outside, please. And can we use 1 component for both scenarios?

2021-09-05 18:30 UTC, yevhenii-moroziuk commented on mobile/HypecrafterMobile/app/components/common/ProjectCard.tsx
> +        <Image style={styles.image} source={{uri: project.imageUrl || 'https://source.unsplash.com/random'}} />
It seems that something is wrong with the linter...

2021-09-05 18:30 UTC, yevhenii-moroziuk commented on mobile/HypecrafterMobile/app/components/common/ProjectCard.tsx
> +    backgroundColor: '#2e333a',
Create global files for colors, fonts, etc.

2021-09-06 09:03 UTC, niksonax commented on mobile/HypecrafterMobile/app/common/enums/category/category.ts
> +export enum CategoryType {
I was trying to make mobile 100% stand alone, so I added this enum here as well

2021-09-06 09:03 UTC, niksonax commented on mobile/HypecrafterMobile/app/common/enums/category/category.ts
> +export enum CategoryType {
> Do we have this enum in shared?

I was trying to make mobile 100% stand alone, so I added this enum here as well

2021-09-06 09:08 UTC, niksonax commented on mobile/HypecrafterMobile/app/App.tsx
> +          ref={(navigatorRef: any) => {
> ref={NavigationService.setTopLevelNavigator} ?

Eliza was adding routing and `any` types as a temporally solution. She will change it

2021-09-06 09:09 UTC, niksonax commented on mobile/HypecrafterMobile/app/components/common/ProjectCard.tsx
> +    backgroundColor: '#2e333a',
> Create global files for colors, fonts, etc.

Created

2021-09-06 09:09 UTC, niksonax commented on mobile/HypecrafterMobile/app/components/common/ProjectCard.tsx
> +        <Image style={styles.image} source={{uri: project.imageUrl || 'https://source.unsplash.com/random'}} />
> It seems that something is wrong with the linter...

Fixed

2021-09-06 09:10 UTC, niksonax commented on mobile/HypecrafterMobile/app/common/enums/projects/projectsCategories.ts
> +declare enum Common {
> do we need declare?

Removed declare

2021-09-06 09:11 UTC, niksonax commented on mobile/HypecrafterMobile/app/components/MainView/screens/PopularScreen.tsx
> +  const renderItem: ListRenderItem<Project> = ({ item }) => (
> This function will be re-created on every render. Since it doesn't use PopularScreen's props, move it outside, please. And can we use 1 component for both scenarios?

Added 1 unified component with `switch case` for different scenarios

2021-09-06 12:05 UTC, yevhenii-moroziuk approved these changes

2021-09-06 12:52 UTC, merged