Add statistics block and generate reports in frontend
BinaryStudioAcademy/bsa-2021-hypecrafter pull request #192
Opened 2021-09-03 20:02 UTC by DarkFlamingo

2021-09-03 20:03 UTC, DarkFlamingo commented
Block style
![image](https://user-images.githubusercontent.com/59978115/132059961-1bbb4fa1-3524-436d-90cc-2f0daa1c9c12.png)
File style
![image](https://user-images.githubusercontent.com/59978115/132060023-f4c02f30-bfa3-4c52-ac75-bd49164572e1.png)

2021-09-05 18:35 UTC, yevhenii-moroziuk requested changes

2021-09-05 18:35 UTC, yevhenii-moroziuk commented on frontend/src/scenes/ProjectPage/components/Statistics/index.tsx
> +            Global Statistics
Localization

2021-09-05 18:35 UTC, yevhenii-moroziuk commented on frontend/src/scenes/ProjectPage/reducer.ts
> +  statistics: Statistics;
Maybe it's better to use undefined instead?

2021-09-05 18:35 UTC, yevhenii-moroziuk commented on frontend/src/services/project.ts
> +  timeInterval
no need to use deconstruction here

2021-09-05 18:35 UTC, yevhenii-moroziuk commented on frontend/src/services/project.ts
> +  console.log(statistics);
log

2021-09-07 13:49 UTC, DarkFlamingo commented on frontend/src/scenes/ProjectPage/reducer.ts
> +  statistics: Statistics;
Instead of the default value of the statistics ?

2021-09-07 16:07 UTC, DarkFlamingo commented on frontend/src/scenes/ProjectPage/reducer.ts
> +  statistics: Statistics;
Using undefined there are some problems with chart js params

2021-09-08 15:59 UTC, yevhenii-moroziuk approved these changes

2021-09-08 19:46 UTC, merged