Feat/edit project page
BinaryStudioAcademy/bsa-2021-hypecrafter pull request #193
Opened 2021-09-04 11:12 UTC by Cuba49

2021-09-05 18:42 UTC, yevhenii-moroziuk requested changes

2021-09-05 18:42 UTC, yevhenii-moroziuk commented on backend/src/data/mappers/mapPrivileges.ts
>    bakersDonation: number[]
If bakersDonation can be null, than use bakersDonation: number[] | null

2021-09-05 18:42 UTC, yevhenii-moroziuk commented on backend/src/services/faq/faq.ts
> +    const tags = await this.#faqRepository.save(faqs);
You can return a promise: 
`return this.#faqRepository.save(faqs);`

2021-09-05 18:42 UTC, yevhenii-moroziuk commented on backend/src/services/project/project.ts
> +    console.log(project);
log

2021-09-05 18:42 UTC, yevhenii-moroziuk commented on backend/src/services/projectPrivilege/projectPrivilege.ts
> +// import { DonatorsPrivilege } from '../../data/entities';
comment

2021-09-05 21:54 UTC, maksim-luzin approved these changes

2021-09-06 11:53 UTC, yevhenii-moroziuk approved these changes

2021-09-06 11:54 UTC, merged