Feature interaction time count of views
BinaryStudioAcademy/bsa-2021-hypecrafter pull request #194
Opened 2021-09-05 18:54 UTC by maksim-luzin

2021-09-06 12:04 UTC, yevhenii-moroziuk requested changes

2021-09-06 12:04 UTC, yevhenii-moroziuk commented on backend/src/services/project/project.ts
> +      ) as unknown as UpdateViewsAndInteractionTime;
Do not use "as unknown as UpdateViewsAndInteractionTime"

2021-09-06 12:04 UTC, yevhenii-moroziuk commented on frontend/src/components/Card/index.tsx
> +/* eslint-disable react/require-default-props */
Seems that some of eslint dependencies have been updated (or the rule was removed), Let's disable this rule in config.

2021-09-06 12:04 UTC, yevhenii-moroziuk commented on frontend/src/helpers/http.ts
> +  const fullUrl = url;
merge develop, please

2021-09-06 12:04 UTC, yevhenii-moroziuk commented on frontend/src/services/project.ts
> +): Promise<Project> => api.get({ url: params.id, params });
it should work in dev

2021-09-06 12:04 UTC, yevhenii-moroziuk commented on frontend/src/services/projects.ts
> +  if (!id || typeof params === 'undefined') throw Error();
do we need this check here?

2021-09-06 15:42 UTC, maksim-luzin commented on backend/src/services/project/project.ts
> +      ) as unknown as UpdateViewsAndInteractionTime;
I will delete it.

2021-09-06 15:49 UTC, maksim-luzin commented on frontend/src/services/project.ts
> +): Promise<Project> => api.get({ url: params.id, params });
I will replace it.

2021-09-06 15:52 UTC, maksim-luzin commented on frontend/src/services/projects.ts
> +  if (!id || typeof params === 'undefined') throw Error();
I will deleted it.

2021-09-06 15:58 UTC, maksim-luzin commented on frontend/src/components/Card/index.tsx
> +/* eslint-disable react/require-default-props */
I added `"react/require-default-props": "off"`

2021-09-06 16:05 UTC, maksim-luzin commented on frontend/src/components/Card/index.tsx
> +/* eslint-disable react/require-default-props */
And I will delete it.

2021-09-08 15:59 UTC, yevhenii-moroziuk approved these changes

2021-09-09 10:54 UTC, merged