add Card component
BinaryStudioAcademy/bsa-2021-hypecrafter pull request #20
Opened 2021-07-29 21:32 UTC by buiiz

2021-07-31 08:54 UTC, mtseluiko approved these changes

2021-08-01 08:31 UTC, yevhenii-moroziuk requested changes

2021-08-01 08:31 UTC, yevhenii-moroziuk commented on frontend/src/components/Card/CardWithLink.tsx
> +const CardComponent: FC<Props> = ({
rename CardComponent  to CardWitLink

2021-08-01 08:31 UTC, yevhenii-moroziuk commented on frontend/src/components/Card/index.tsx
> +  </article>
This seems to be the ProjectCard.

Let's create 2 separate components: Card and ProjectCard.
The card will be a common component with basic styles, and the ProjectCard will use the card and pass content there as a child.

2021-08-01 22:04 UTC, buiiz commented on frontend/src/components/Card/CardWithLink.tsx
> +const CardComponent: FC<Props> = ({
done

2021-08-01 22:04 UTC, buiiz commented on frontend/src/components/Card/index.tsx
> +  </article>
done

2021-08-02 07:41 UTC, yevhenii-moroziuk approved these changes

2021-08-02 11:06 UTC, merged