Feat/chart component
BinaryStudioAcademy/bsa-2021-hypecrafter pull request #21
Opened 2021-07-30 06:28 UTC by dgorkavyi

2021-07-30 14:06 UTC, yevhenii-moroziuk requested changes

2021-07-30 14:06 UTC, yevhenii-moroziuk commented on frontend/package.json
> +    "@types/query-string": "^6.3.0",
no need for this definition since it doesn't work

2021-07-30 14:06 UTC, yevhenii-moroziuk commented on frontend/src/components/Chart/Chart.tsx
> +const testData = {
move the test data out the component

2021-07-30 14:06 UTC, yevhenii-moroziuk commented on frontend/src/components/Chart/Chart.tsx
> +type TDataSet = [
```
type DataItem = {
    label: string;
    data: number[];
    fill?: boolean;
    backgroundColor?: string;
    borderColor?: string;
  }
```

Do not use I prefix for Types and interfaces

2021-07-30 14:06 UTC, yevhenii-moroziuk commented on frontend/src/components/Chart/Chart.tsx
> +  data?: TDataSet | any;
Please use the interface here for code consistency. Do not use any and make type and data required.

2021-07-30 14:06 UTC, yevhenii-moroziuk commented on frontend/src/components/Chart/Chart.tsx
> +
Rename to Chart, remove console.log and react fragment.

2021-07-31 10:19 UTC, buiiz commented on frontend/src/components/Chart/Chart.tsx
> +const Chart: React.FC<ChartProps> = ({ type, dataSets, labels }) => (
nit: it would be good to set default values to optional props or make them required

2021-07-31 19:51 UTC, dgorkavyi commented on frontend/src/components/Chart/Chart.tsx
> +const Chart: React.FC<ChartProps> = ({ type, dataSets, labels }) => (
Sorry, forgot to remove the "?" in the interface ChartProps. All of them are needed. By the way if you need some default values to see how it works, you can get it from testprops.ts

2021-07-31 20:13 UTC, yevhenii-moroziuk commented on frontend/src/components/Chart/Chart.tsx
> +const Chart: React.FC<ChartProps> = ({ type, dataSets, labels }) => (
Let's add optional property options and use defaultProps as default. Please try to create an interface based on documentation for options

2021-08-02 11:57 UTC, yevhenii-moroziuk approved these changes

2021-08-03 08:26 UTC, closed without merging

2021-08-03 08:28 UTC, dgorkavyi commented
Conflicts were fixed, the merge was done from the terminal, the commit is in the logs