Create modal window
BinaryStudioAcademy/bsa-2021-hypecrafter pull request #23
Opened 2021-07-30 17:00 UTC by eluyema

common modal window

2021-07-31 08:55 UTC, mtseluiko approved these changes

2021-07-31 19:59 UTC, yevhenii-moroziuk requested changes

2021-07-31 19:59 UTC, yevhenii-moroziuk commented on frontend/src/components/ModalWindow/index.tsx
> +/*  eslint linebreak-style: ["error", "windows"]    */
Do we need this? Do you use CRLF instead of LF?

2021-07-31 19:59 UTC, yevhenii-moroziuk commented on frontend/src/components/ModalWindow/index.tsx
> +  footer: ReactNode | null;
Make footer optional 

```
(footer?: ReactNode)
...
{footer && <Modal.Footer>{footer}</Modal.Footer>}
```

2021-07-31 19:59 UTC, yevhenii-moroziuk commented on frontend/src/components/ModalWindow/index.tsx
> +/*  eslint linebreak-style: ["error", "windows"]    */
Also, add some basic styles (our background color)

2021-08-01 08:24 UTC, yevhenii-moroziuk commented on frontend/src/components/ModalWindow/index.tsx
> +  showTrigger(): void;
rename showTrigger to onHide

2021-08-01 15:51 UTC, yevhenii-moroziuk approved these changes

2021-08-01 16:30 UTC, merged