Feat/user page
BinaryStudioAcademy/bsa-2021-hypecrafter pull request #35
Opened 2021-08-03 16:40 UTC by niksonax

2021-08-04 14:32 UTC, yevhenii-moroziuk requested changes
Is it optimised for mobile phones?

2021-08-04 14:32 UTC, yevhenii-moroziuk commented on frontend/src/components/Main/index.tsx
> +        size="user-page"
It's a shared component, so rename it, eg extra-wide.

2021-08-04 14:32 UTC, yevhenii-moroziuk commented on frontend/src/scenes/UserPage/components/Body.tsx
> +  if (target === 'projects') {
Let's use component Tab here

2021-08-04 14:32 UTC, yevhenii-moroziuk commented on frontend/src/scenes/UserPage/components/Body.tsx
> +        percent={Math.floor((project.donated / project.goal) * 100)}
This function might be used in multiple places, move it to helpers

2021-08-04 14:32 UTC, yevhenii-moroziuk commented on frontend/src/scenes/UserPage/components/Header.tsx
> +          {aboutMe} {/* Make 240 symbols limit */}
comment

2021-08-05 06:22 UTC, niksonax commented
> Is it optimised for mobile phones?



> Is it optimised for mobile phones?
No, it's not. But I can work on it today

2021-08-05 06:23 UTC, niksonax commented
> Is it optimised for mobile phones?

No, it`s not. I can work on it today to make it adaptive

2021-08-05 07:55 UTC, merged