Add funds page
BinaryStudioAcademy/bsa-2021-hypecrafter pull request #36
Opened 2021-08-04 01:54 UTC by eluyema

There is no functionality yet, mostly only layout

2021-08-04 19:21 UTC, yevhenii-moroziuk requested changes

2021-08-04 19:21 UTC, yevhenii-moroziuk commented on frontend/src/common/enums/routes.ts
> +  ADDFUNDS = '/addfunds',
Let's use /add-funds

2021-08-04 19:21 UTC, yevhenii-moroziuk commented on frontend/src/components/Routing/index.tsx
> +      <Route path={Routes.LOGIN} exact component={LoginPage} />
Just add Funds page. It will be private page.

2021-08-04 19:21 UTC, yevhenii-moroziuk commented on frontend/src/components/Routing/index.tsx
> +//      <Route path={Routes.HOME} exact component={Main} />
comment

2021-08-04 19:21 UTC, yevhenii-moroziuk commented on frontend/src/scenes/Wallet/CustomFund/index.tsx
> +  const { t, i18n } = useTranslation();
Use here useLocalization hook (You need to merge develop branch). Also, you need to update LocaleKeys type, just run command: `generate:keys` in frontend directory.

2021-08-04 19:21 UTC, yevhenii-moroziuk commented on frontend/src/scenes/Wallet/CustomFund/index.tsx
> +          <Form.Control
Let's use our Input component

2021-08-04 19:21 UTC, yevhenii-moroziuk commented on frontend/src/scenes/Wallet/CustomFund/index.tsx
> +        <button type="submit"> {t('Add funds')}</button>
use our button

2021-08-04 19:21 UTC, yevhenii-moroziuk commented on frontend/src/scenes/Wallet/Fund/styles.module.scss
> +    background: #12c2e9; /* fallback for old browsers */
Did you copy the styles from somewhere?

2021-08-04 19:48 UTC, eluyema commented on frontend/src/scenes/Wallet/Fund/styles.module.scss
> +    background: #12c2e9; /* fallback for old browsers */
I use generator for gradient background

2021-08-04 20:18 UTC, eluyema commented on frontend/src/components/Routing/index.tsx
> +      <Route path={Routes.LOGIN} exact component={LoginPage} />
What it's mean?

2021-08-05 05:15 UTC, yevhenii-moroziuk commented on frontend/src/components/Routing/index.tsx
> +      <Route path={Routes.LOGIN} exact component={LoginPage} />
It seems, that you added 3 new routes (Home, AddFunds, Login) and imported Switch the second time. I guess it was a merge conflict. Just add only 1 page, and wrap it in private route:
 `<PrivateRoute path={Routes.ADDFUNDS} exact component={FundsPage} />`

2021-08-05 15:12 UTC, eluyema commented on frontend/src/scenes/Wallet/CustomFund/index.tsx
> +          <Form.Control
Our input component not have type for number

2021-08-05 15:55 UTC, yevhenii-moroziuk approved these changes

2021-08-05 16:07 UTC, merged