Frontend: implement i18n
BinaryStudioAcademy/bsa-2021-hypecrafter pull request #4
Opened 2021-07-27 17:40 UTC by Cuba49

2021-07-27 17:56 UTC, mtseluiko requested changes

2021-07-27 17:56 UTC, mtseluiko commented on frontend/src/services/i18n.ts
> +      en: {
Move dictionaries to separate files

2021-07-27 17:56 UTC, mtseluiko commented on frontend/src/components/TranslateExample/index.tsx
> +      <Button onClick={() => i18n.changeLanguage(i18n.language === 'ua' ? 'en' : 'ua')}>
Please, don't create a new function just in the same place where you are passing this callback to a component. It might decrease performance because of unneeded rerenders.

2021-07-27 17:56 UTC, mtseluiko commented on frontend/src/components/TranslateExample/index.tsx
> +      <Button onClick={() => i18n.changeLanguage(i18n.language === 'ua' ? 'en' : 'ua')}>
Move languages constants to enums

2021-07-27 17:56 UTC, mtseluiko commented on shared/package.json
> +    "build": "npm run build:ts && copy package.json build"
Good point! But could you please remove this fix from this PR, create a new task with a new PR? The fix is good for windows, but in this case, it won't work on Linux. It seems the cross-platform solution is something like this: https://stackoverflow.com/a/38859090

2021-07-27 19:37 UTC, yevhenii-moroziuk commented on frontend/src/components/TranslateExample/index.tsx
> +
Remove this empty line

2021-07-28 07:28 UTC, yevhenii-moroziuk commented on frontend/src/services/i18n.ts
> +    fallbackLng: 'en',
Could you please use enum here as well?

2021-07-28 07:32 UTC, mtseluiko approved these changes

2021-07-28 07:34 UTC, yevhenii-moroziuk requested changes

2021-07-28 07:34 UTC, yevhenii-moroziuk commented on frontend/src/services/i18n.ts
> +    fallbackLng: 'en',
Could you please use enum here as well?

2021-07-28 07:39 UTC, yevhenii-moroziuk approved these changes

2021-07-28 07:40 UTC, merged