Feature add entity
BinaryStudioAcademy/bsa-2021-hypecrafter pull request #45
Opened 2021-08-05 06:52 UTC by maksim-luzin

Added tables for the backend according to the scheme and taking into account the wishes.

2021-08-05 13:03 UTC, mtseluiko commented on backend/src/data/entities/fAQ.ts
> +import { Entity, Column, ManyToOne } from 'typeorm';
Rename this file to faq

2021-08-05 13:11 UTC, yevhenii-moroziuk requested changes

2021-08-05 13:11 UTC, yevhenii-moroziuk commented on backend/src/data/entities/project.ts
> +  @Column({ type: 'int' })
This field should be real

2021-08-05 13:11 UTC, yevhenii-moroziuk commented on backend/src/data/entities/achievement.ts
> +  userAchievements!: UserAchievement[];
Why do we need exclamation point?

2021-08-05 13:11 UTC, yevhenii-moroziuk commented on backend/src/data/entities/fAQ.ts
> +import { Entity, Column, ManyToOne } from 'typeorm';
Let it be faq.ts

2021-08-06 10:20 UTC, maksim-luzin commented on backend/src/data/entities/fAQ.ts
> +import { Entity, Column, ManyToOne } from 'typeorm';
I renamed.

2021-08-06 10:21 UTC, maksim-luzin commented on backend/src/data/entities/project.ts
> +  @Column({ type: 'int' })
I did it real.

2021-08-06 10:22 UTC, maksim-luzin commented on backend/src/data/entities/achievement.ts
> +  userAchievements!: UserAchievement[];
I deleted exclamation point.

2021-08-06 10:24 UTC, yevhenii-moroziuk commented on backend/src/data/entities/project.ts
> +  @Column({ type: 'int' })
Have you changed totalInteractionTime? It seems no.

2021-08-09 05:38 UTC, yevhenii-moroziuk approved these changes

2021-08-09 08:38 UTC, merged