add main page
BinaryStudioAcademy/bsa-2021-hypecrafter pull request #46
Opened 2021-08-05 11:51 UTC by dolphin323

2021-08-06 13:57 UTC, yevhenii-moroziuk requested changes

2021-08-06 13:57 UTC, yevhenii-moroziuk commented on frontend/src/reducers/projects.ts
> +import { Project } from '../common/types';
Let's move it to mainPage scene

2021-08-06 13:57 UTC, yevhenii-moroziuk commented on frontend/src/scenes/MainPage/index.tsx
> +            Do you have a good and well thought-out idea and are you ready
Use TFunction please. The key can be: "Do you have a good and well thought-out idea and are you ready_"

2021-08-06 13:57 UTC, yevhenii-moroziuk commented on frontend/src/scenes/MainPage/index.tsx
> +            <Button type="button" isOutline>Help Project</Button>
just outline

2021-08-06 13:57 UTC, yevhenii-moroziuk commented on frontend/src/components/Button/styles.module.scss
> +  border: solid 2px transparent;
What if I select <Button type="secondary" outline />?

2021-08-06 14:07 UTC, yevhenii-moroziuk requested changes

2021-08-06 14:07 UTC, yevhenii-moroziuk commented on frontend/src/scenes/MainPage/index.tsx
> +    <div className={classes.root}>
It would be nice to use not only divs

2021-08-10 11:42 UTC, mtseluiko requested changes
resolve conflicts

2021-08-11 18:28 UTC, yevhenii-moroziuk requested changes

2021-08-11 18:28 UTC, yevhenii-moroziuk commented on frontend/src/scenes/MainPage/index.tsx
> +                  to="/"
to={`/projects/${project.id}`}
...
image={project.image}

2021-08-11 18:28 UTC, yevhenii-moroziuk commented on backend/src/data/repositories/project.ts
> +      .select(`amount as donated,
Formatting

2021-08-12 04:51 UTC, yevhenii-moroziuk approved these changes

2021-08-12 05:04 UTC, yevhenii-moroziuk requested changes

2021-08-12 05:04 UTC, yevhenii-moroziuk commented on frontend/src/scenes/MainPage/index.tsx
> +    dispatch(actions.fetchPopularAndRecommendedProjectsAction());
redundant dispatch

2021-08-12 07:28 UTC, yevhenii-moroziuk approved these changes

2021-08-12 07:29 UTC, merged