Page of transactions list
BinaryStudioAcademy/bsa-2021-hypecrafter pull request #53
Opened 2021-08-07 02:05 UTC by eluyema

2021-08-07 16:44 UTC, yevhenii-moroziuk requested changes

2021-08-07 16:44 UTC, yevhenii-moroziuk commented on frontend/src/scenes/Wallet/Transactions/index.tsx
> +        <Link to="/"> {t('Home')}</Link>
Use enum Routes

2021-08-07 16:44 UTC, yevhenii-moroziuk commented on frontend/src/scenes/Wallet/Transactions/index.tsx
> +  const columns: Column<Data>[] = useMemo(
Let's create file utils.ts and move this config there.

2021-08-07 16:44 UTC, yevhenii-moroziuk commented on frontend/src/scenes/Wallet/Transactions/styles.module.scss
> +        }
Is it possible to configure width in columns[]?

2021-08-07 16:44 UTC, yevhenii-moroziuk commented on frontend/src/scenes/Wallet/Transactions/index.tsx
> +                        )}
Let's create a function renderCell with switch-case inside.

2021-08-07 16:44 UTC, yevhenii-moroziuk commented on frontend/src/scenes/Wallet/Transactions/index.tsx
> +  const data: Data[] = useMemo(() => [...mock], []);
Let's take this data from reducer

2021-08-07 16:44 UTC, yevhenii-moroziuk commented on frontend/src/scenes/Wallet/Transactions/index.tsx
> +      <Table
Please add pagination for the table.

2021-08-07 17:43 UTC, eluyema commented on frontend/src/scenes/Wallet/Transactions/styles.module.scss
> +        }
What is columns[] ?

2021-08-07 17:48 UTC, yevhenii-moroziuk commented on frontend/src/scenes/Wallet/Transactions/styles.module.scss
> +        }
`const columns: Column<Data>[] = useMemo(
...
    () => [
      {
        Header: t('Date'),
        accessor: 'date'
      },
....
]`

2021-08-07 17:51 UTC, eluyema commented on frontend/src/scenes/Wallet/Transactions/styles.module.scss
> +        }
I want add pagination after backend. I thought load new page of table by each get request(click on button). Can i stay it like this until backend will not ready?

2021-08-07 17:54 UTC, eluyema commented on frontend/src/scenes/Wallet/Transactions/index.tsx
> +      <Table
I want add pagination after backend. I thought load new page of table by each get request(click on button). Can i stay it like this until backend will not ready?

2021-08-07 17:58 UTC, eluyema commented on frontend/src/scenes/Wallet/Transactions/styles.module.scss
> +        }
I thing it cannot, because react-table no being in charge of UI (it is written in the documentation of react-table)

2021-08-09 01:12 UTC, eluyema commented on frontend/src/scenes/Wallet/Transactions/index.tsx
> +  const columns: Column<Data>[] = useMemo(
I don't know how it do. Titles in the table should be localized, but( if i all know correctly) we can do it only with hooks useLocalization. I can't move columns to utils.ts.

2021-08-09 08:36 UTC, yevhenii-moroziuk commented on frontend/src/scenes/Wallet/Transactions/styles.module.scss
> +        }
https://stackoverflow.com/questions/62152372/changing-column-width-in-react-table

2021-08-09 08:36 UTC, yevhenii-moroziuk commented on frontend/src/scenes/Wallet/Transactions/index.tsx
> +  const columns: Column<Data>[] = useMemo(
You can use function getColumns(t)

2021-08-09 08:59 UTC, yevhenii-moroziuk commented on frontend/src/scenes/Wallet/Transactions/index.tsx
> +      <Table
Ok, then create a new backend ticket for this page and add a note(add pagination)

2021-08-15 14:58 UTC, yevhenii-moroziuk approved these changes
@mtseluiko, do not merge it before the backend part, please

2021-08-17 07:17 UTC, merged