Add use leave page.
BinaryStudioAcademy/bsa-2021-hypecrafter pull request #60
Opened 2021-08-10 06:44 UTC by maksim-luzin

2021-08-12 04:50 UTC, yevhenii-moroziuk requested changes

2021-08-12 04:50 UTC, yevhenii-moroziuk commented on frontend/src/components/LeavePage/index.tsx
> +interface IUseLeavePage {
Just Props

2021-08-12 04:50 UTC, yevhenii-moroziuk commented on frontend/src/components/LeavePage/index.tsx
> +export default LeavePage;
Please provide example. Maybe we can use this component as Container and path the children here, eg:

```
<LeavePage {...props}>
  <CreateProject />
</LeavePage >
```

2021-08-12 13:03 UTC, maksim-luzin commented on frontend/src/components/LeavePage/index.tsx
> +export default LeavePage;
This is an example of use.
    <LeavePage
      message="Your message when blocking. Default 'You must completely create a project.'"
      isBlocking={true/false } Default true.
    >
      <CreateProject />
    </LeavePage >

2021-08-13 06:43 UTC, yevhenii-moroziuk requested changes

2021-08-13 06:43 UTC, yevhenii-moroziuk commented on frontend/src/components/LeavePage/index.tsx
> +  */
Please move it to Line 9 and use Doc comments https://typedoc.org/guides/doccomments/

2021-08-17 07:49 UTC, merged