Connect User Page to the Backend
BinaryStudioAcademy/bsa-2021-hypecrafter pull request #63
Opened 2021-08-10 09:09 UTC by niksonax

2021-08-10 11:45 UTC, mtseluiko commented on backend/src/services/user/user.ts
> +    console.log('GET BY ID');
remove console.log

2021-08-10 11:45 UTC, mtseluiko commented on docker-compose.rabbitmq.yml
> +  rabbitmq:
why?

2021-08-11 09:25 UTC, yevhenii-moroziuk requested changes

2021-08-11 09:25 UTC, yevhenii-moroziuk commented on frontend/src/services/users.ts
> +// export const getUser = (id: string) => fetch(`http://localhost:3002/users/${id}`).then(response => response.json());
comment

2021-08-11 11:04 UTC, yevhenii-moroziuk approved these changes

2021-08-11 11:04 UTC, merged