Change type of swagger file from JSON to YALM
BinaryStudioAcademy/bsa-2021-hypecrafter pull request #69
Opened 2021-08-11 02:27 UTC by eluyema

2021-08-11 05:59 UTC, yevhenii-moroziuk requested changes

2021-08-11 05:59 UTC, yevhenii-moroziuk commented on gateway/package.json
> +    "@types/yamljs": "^0.2.31",
Move this to devDependencies

2021-08-11 05:59 UTC, yevhenii-moroziuk commented on gateway/src/api/middlewares/index.ts
> +import express, { Express, json } from "express";
Do you have prettier? If so, change the config to use single quotes. Do you have eslint installed?

2021-08-11 07:23 UTC, mtseluiko commented on gateway/openApiDocumentation.yaml
> +  - url: http://localhost:3001/api
Could you also add the staging server URL?

2021-08-11 17:33 UTC, yevhenii-moroziuk approved these changes

2021-08-12 11:25 UTC, mtseluiko commented
resolve conflicts, please

2021-08-12 18:42 UTC, merged