add http-helper
BinaryStudioAcademy/bsa-2021-hypecrafter pull request #7
Opened 2021-07-28 14:14 UTC by DarkFlamingo

2021-07-28 14:21 UTC, mtseluiko requested changes

2021-07-28 14:21 UTC, mtseluiko commented on frontend/src/helpers/http.ts
> +  const token = localStorage.getItem('ACCESS_TOCKEN');
fix typo

2021-07-28 14:21 UTC, mtseluiko commented on frontend/src/helpers/http.ts
> +  let fullUrl: string = url;
use early return instead of variable

2021-07-29 06:22 UTC, yevhenii-moroziuk requested changes

2021-07-29 06:22 UTC, yevhenii-moroziuk commented on frontend/src/helpers/http.ts
> +  const token = localStorage.getItem('ACCESS_TOKEN');
Let's use an enum for StorageKeys

2021-07-29 06:22 UTC, yevhenii-moroziuk commented on frontend/src/helpers/http.ts
> +  return url;
1. we will use the "external" flag to fetch from non-API routes. Eg:
isExternal => URL
otherwise => API_URL/url
btw, lets rename this property to isExternal
2. `${getEnv('REACT_APP_SERVER_URL')}/${url}` used 2 times,
create the variable, and use env.ts.

2021-07-29 10:17 UTC, yevhenii-moroziuk approved these changes

2021-07-29 14:47 UTC, merged