Add trends page
BinaryStudioAcademy/bsa-2021-hypecrafter pull request #73
Opened 2021-08-11 06:50 UTC by DarkFlamingo

2021-08-11 07:14 UTC, DarkFlamingo commented
Загальний вигляд 
![image](https://user-images.githubusercontent.com/59978115/128985766-74a35272-7e27-48ab-8c36-15010b8067e0.png)
![image](https://user-images.githubusercontent.com/59978115/128985850-faa1faaa-8f7a-48d9-8538-632f5f7ff645.png)

2021-08-11 07:39 UTC, yevhenii-moroziuk requested changes

2021-08-11 07:39 UTC, yevhenii-moroziuk commented on frontend/src/scenes/TrendsPage/components/ProjectsChart/CategorySubtitle/style.module.scss
> +  text-decoration: none;
These 2 classes have almost the same props, create subtopic-item with common props and subtopic-item-active with color

2021-08-11 07:39 UTC, yevhenii-moroziuk commented on frontend/src/scenes/TrendsPage/components/ProjectsChart/CategorySubtitle/index.tsx
> +      onClick={handleClick}
It's a bad practice to use onClick on div, use button and reset-button mixin

2021-08-11 07:39 UTC, yevhenii-moroziuk commented on frontend/src/scenes/TrendsPage/components/ProjectsChart/index.tsx
> +    <div className={classes.item}>
It would be nice to use semantc tags, eg: section, header, h2, ...
And don't forget to use localization

2021-08-11 07:39 UTC, yevhenii-moroziuk commented
> General form:
> ![image](https://user-images.githubusercontent.com/59978115/128985766-74a35272-7e27-48ab-8c36-15010b8067e0.png)
> ![image](https://user-images.githubusercontent.com/59978115/128986755-ea4d2e55-3dd4-4b04-b4c3-bfd4c2d1da36.png)

2021-08-11 12:30 UTC, yevhenii-moroziuk requested changes
You need to update locale keys type

2021-08-11 16:04 UTC, yevhenii-moroziuk requested changes

2021-08-11 16:04 UTC, yevhenii-moroziuk commented on frontend/src/scenes/TrendsPage/components/ProjectsChart/CategorySubtitle/index.tsx
> +          ? `${classes['subtopic-item']} ${classes['subtopic-item-active']}`
use classname here: eg classnames({ classes['subtopic-item']: true, classes['subtopic-item-active']: isSelected }

2021-08-11 16:04 UTC, yevhenii-moroziuk commented on frontend/src/scenes/TrendsPage/options/ProjectsOptions.ts
> +    colors.push(`hsl(${360 * Math.random()},100%,50%)`);
Thi function could be moved to helpers. Also, same this sortArray

2021-08-12 09:41 UTC, yevhenii-moroziuk approved these changes

2021-08-12 11:24 UTC, merged