Feature use auth hook
BinaryStudioAcademy/bsa-2021-hypecrafter pull request #74
Opened 2021-08-11 07:37 UTC by maksim-luzin

2021-08-11 17:40 UTC, yevhenii-moroziuk requested changes

2021-08-11 17:40 UTC, yevhenii-moroziuk commented on frontend/src/hooks/useAuth.ts
> +  const id = useSelector(({ auth: { user } }: StoreState) => {
Use our typedSelector please. Also, return { id: undefined, isAuthorized: false } if !user

2021-08-11 20:53 UTC, maksim-luzin commented on frontend/src/hooks/useAuth.ts
> +  const id = useSelector(({ auth: { user } }: StoreState) => {
Thank you for you advice.

2021-08-12 04:44 UTC, yevhenii-moroziuk approved these changes

2021-08-12 04:44 UTC, merged