Edit header
BinaryStudioAcademy/bsa-2021-hypecrafter pull request #88
Opened 2021-08-15 23:46 UTC by maksim-luzin

2021-08-16 06:18 UTC, yevhenii-moroziuk requested changes

2021-08-16 06:18 UTC, yevhenii-moroziuk commented on frontend/src/components/Header/index.tsx
> +
Such logic should be inside useEffect and take a look on useScroll, please

2021-08-16 06:18 UTC, yevhenii-moroziuk commented on frontend/src/components/Header/index.tsx
> +                <Link to={Routes.PROFILE}>View account</Link>
Localization

2021-08-16 06:18 UTC, yevhenii-moroziuk commented on frontend/src/components/Header/index.tsx
> +                  onTouchStart={handleProjectsMenuForMobile}
Do not use onClick on div's, use button instead

2021-08-16 06:18 UTC, yevhenii-moroziuk commented on frontend/src/components/Header/index.tsx
> +/* eslint-disable jsx-a11y/click-events-have-key-events */
remove this

2021-08-17 13:36 UTC, maksim-luzin commented on frontend/src/components/Header/index.tsx
> +                <Link to={Routes.PROFILE}>View account</Link>
I replaced.

2021-08-18 10:26 UTC, merged