add page 404 gateway
BinaryStudioAcademy/bsa-2021-hypecrafter pull request #89
Opened 2021-08-16 08:17 UTC by dgorkavyi

2021-08-17 13:26 UTC, yevhenii-moroziuk requested changes

2021-08-17 13:26 UTC, yevhenii-moroziuk commented on gateway/src/api/middlewares/authorization.ts
> -    : jwtMiddleware(req, res, next)));
Will authorization work?

2021-08-18 10:50 UTC, mtseluiko commented on gateway/src/api/middlewares/authorization.ts
> -    : jwtMiddleware(req, res, next)));
not sure, maybe this PR should be merged after demo

2021-08-25 05:56 UTC, yevhenii-moroziuk approved these changes

2021-08-25 13:56 UTC, yevhenii-moroziuk approved these changes

2021-08-25 14:04 UTC, merged