Frontend: add input component
BinaryStudioAcademy/bsa-2021-hypecrafter pull request #9
Opened 2021-07-28 16:29 UTC by niksonax

2021-07-28 19:25 UTC, mtseluiko commented on frontend/src/components/Input/index.tsx
> +import classes from './styles.module.scss'; // add base styles (border)
remove comment (try don't use comments at all, only if some issue is really complicated)

2021-07-28 19:25 UTC, mtseluiko commented on frontend/src/components/Main/index.tsx
> +            errorMessage="Error expample."
fix typo

2021-07-28 19:26 UTC, mtseluiko commented on frontend/src/components/Input/index.tsx
> +        { errorMessage ? <span className={classes.errorMessage}> {errorMessage} </span> : null }
btw, in such cases, you can use { errorMessage && <span ...
https://ru.reactjs.org/docs/conditional-rendering.html#inline-if-with-logical--operator

2021-07-29 06:31 UTC, yevhenii-moroziuk requested changes

2021-07-29 06:31 UTC, yevhenii-moroziuk commented on frontend/src/components/Input/index.tsx
> +      { label ? <div className={classes.inputLabel}> {label} </div> : null }
Use FormLabel from bootstrap, add htmlFor property, eg:
Boolean(label) && <FormLabel htmlFor={id} className={classes['input-label']}>{label}</FormLabel>}

2021-07-29 06:31 UTC, yevhenii-moroziuk commented on frontend/src/components/Input/index.tsx
> +    <>
Move label and errorMessageContainer inside InputGroup and remove react fragment

2021-07-29 06:31 UTC, yevhenii-moroziuk commented on frontend/src/components/Input/styles.module.scss
> +.inputLabel {
Do not use camelCase for classes. Use BEM or kebab-case. In jsx it will be classes['input-label']

2021-07-29 07:25 UTC, niksonax commented on frontend/src/components/Input/index.tsx
> +    <>
InputGroup using flex row to display items inside it. So if I do it label, input and error message will display in one row

2021-07-29 10:49 UTC, yevhenii-moroziuk approved these changes

2021-07-29 12:20 UTC, merged